name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [".github/labels.yml"]

jobs:
  sync:
    if: github.repository == 'thakira-dz/3as-terminology'
    runs-on: ubuntu-latest

    steps:
      - name: Sync labels
        uses: r7kamura/github-label-sync-action@v0
        with:
          allow_added_labels: "true"
